import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {makeMyView} from './model.js?v=0340';
import {createRenderPerformance} from '../render-performance.js?v=0260';

const PAPER='#eaeae2';
function environment(renderer){const c=document.createElement('canvas');c.width=1024;c.height=512;const x=c.getContext('2d'),gradient=x.createLinearGradient(0,0,0,512);gradient.addColorStop(0,'#e3e4dc');gradient.addColorStop(.48,'#929c9a');gradient.addColorStop(.57,'#545b5b');gradient.addColorStop(1,'#ccc9be');x.fillStyle=gradient;x.fillRect(0,0,1024,512);for(const [a,b,w,h] of [[130,60,140,250],[635,55,170,130]]){x.fillStyle='#fffdf0';x.fillRect(a,b,w,h);}const map=new T.CanvasTexture(c);map.colorSpace=T.SRGBColorSpace;map.mapping=T.EquirectangularReflectionMapping;const pm=new T.PMREMGenerator(renderer),env=pm.fromEquirectangular(map);map.dispose();pm.dispose();return env;}
/** Shared exhibition interaction pattern, with this work's own light and cameras. */
export function createMyViewViewer(canvas,{onReady=()=>{},onError=()=>{}}={}){
  const build=new URLSearchParams(location.search).get('build')==='1',reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
  const renderer=new T.WebGLRenderer({canvas,alpha:true,antialias:true,preserveDrawingBuffer:build,powerPreference:'low-power'});renderer.outputColorSpace=T.SRGBColorSpace;renderer.setClearColor(PAPER,0);renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.12;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;
  const scene=new T.Scene(),camera=new T.PerspectiveCamera(34,1,.1,70),world=makeMyView();scene.add(world.root);const env=environment(renderer);scene.environment=env.texture;scene.environmentIntensity=.40;
  scene.add(new T.HemisphereLight('#f6f5ea','#767c7d',.68));
  const key=new T.DirectionalLight('#fff7eb',2.65);key.position.set(-4.2,6,5.8);key.castShadow=true;key.shadow.mapSize.set(2048,2048);key.shadow.normalBias=.006;key.shadow.bias=-.00015;key.shadow.radius=3;Object.assign(key.shadow.camera,{left:-3,right:3,top:3,bottom:-3,near:1,far:23});scene.add(key);
  const fill=new T.DirectionalLight('#d8e7e5',.68);fill.position.set(5.3,1.4,3);scene.add(fill);const reverseLight=new T.DirectionalLight('#eee9df',1.15);reverseLight.position.set(2.8,3.8,-5.5);scene.add(reverseLight);
  const controls=new OrbitControls(camera,canvas);controls.enablePan=false;controls.enableDamping=!reduced;controls.dampingFactor=.11;controls.rotateSpeed=.60;controls.minDistance=build?.65:1.3;controls.maxDistance=35;
  const clay=new T.MeshStandardMaterial({color:'#bebdb3',roughness:.93,side:T.DoubleSide}),abort=new AbortController(),fitCache=new Map();
  let raf=0,disposed=false,lost=false,suspended=false,inView=true,ready=false,turn=false,separated=false,amount=0,fitDistance=0,detail=null,view='front',light='studio',frames=0,last=performance.now(),dirty=true;
  const policy=createRenderPerformance({canvas,renderer,build,maxDpr:1.6,mobileMaxDpr:1.3,buildDpr:2,onChange:()=>{resize();invalidate();}});
  const visible=()=>inView||Boolean(canvas.closest('.exhibit-immersive[open]'));
  function diagnostics(now,force=false){if(!policy.shouldWriteDiagnostics(now,force))return;Object.assign(canvas.dataset,{ready:String(ready),title:'以我之见',version:world.root.userData.sceneVersion,view,detail:detail||'',frames:String(frames),solidCore:'true',bodyRadius:String(world.root.userData.bodyRadius),bodyAxes:'1,1,1',layers:String(world.groups.length),drawCalls:String(renderer.info.render.calls),triangles:String(renderer.info.render.triangles),modelMeshes:String(world.root.userData.meshCount),modelTriangles:String(world.root.userData.triangleCount),patches:String(world.root.userData.patchCount),cords:String(world.root.userData.cordCount),autoRotate:String(turn),separated:String(separated),separation:amount.toFixed(4),camera:camera.position.toArray().map(x=>x.toFixed(4)).join(','),worldRotation:world.root.rotation.y.toFixed(5),study:String(scene.overrideMaterial===clay),light,suspended:String(suspended),visibleSurface:String(visible())});}
  function invalidate(force=false){if(force===true)dirty=true;if(!raf&&!disposed&&!lost&&!suspended&&!document.hidden)raf=requestAnimationFrame(render);}
  function render(now){raf=0;if(disposed||lost||suspended||document.hidden)return;const dt=Math.min((now-last)/1000,.08);last=now;const animate=visible()&&!reduced;if(turn&&animate)world.root.rotation.y+=dt*.10;const goal=+separated,previous=amount;amount=reduced?goal:T.MathUtils.damp(amount,goal,9,dt);if(Math.abs(amount-goal)<.001)amount=goal;if(amount!==previous)policy.invalidateShadow();world.setSeparated(amount);const changed=controls.update();if(changed)policy.noteInteraction();policy.beforeRender(now,changed||turn||amount!==goal);renderer.render(scene,camera);frames++;diagnostics(now,dirty||(amount!==previous&&amount===goal));dirty=false;if((animate&&turn)||changed||amount!==goal)invalidate();}
  function fit(preserve=false){if(detail){camera.updateProjectionMatrix();return;}const relative=preserve&&fitDistance?camera.position.distanceTo(controls.target)/fitDistance:1,dir=camera.position.clone().sub(controls.target).normalize(),right=new T.Vector3().crossVectors(camera.up,dir).normalize(),up=new T.Vector3().crossVectors(dir,right).normalize(),tan=Math.tan(T.MathUtils.degToRad(camera.fov)/2),k=[camera.aspect,...dir.toArray(),world.root.rotation.y,amount].map(x=>x.toFixed(5)).join('/');let distance=fitCache.get(k);if(distance===undefined){distance=0;const p=new T.Vector3();world.root.updateMatrixWorld(true);world.root.traverse(o=>{if(!o.isMesh||!o.visible)return;const a=o.geometry.attributes.position;for(let i=0;i<a.count;i+=2){p.fromBufferAttribute(a,i).applyMatrix4(o.matrixWorld).sub(controls.target);const near=p.dot(dir);distance=Math.max(distance,near+Math.abs(p.dot(up))*1.085/tan,near+Math.abs(p.dot(right))*1.085/(tan*camera.aspect));}});if(fitCache.size>=20)fitCache.clear();fitCache.set(k,distance);}fitDistance=Math.max(3,distance);camera.position.copy(controls.target).addScaledVector(dir,fitDistance*relative);camera.updateProjectionMatrix();}
  function stop(){const damping=controls.enableDamping;controls.enableDamping=false;controls.update();controls.enableDamping=damping;turn=false;}
  function setView(name){stop();view=['front','side','back'].includes(name)?name:'front';detail=null;world.root.rotation.set(0,0,0);controls.target.set(0,-.02,0);camera.position.set(...(view==='front'?[.5,1.0,12]:view==='side'?[12,.8,.3]:[-.6,.9,-12]));camera.fov=34;fit();controls.update();policy.invalidateShadow();invalidate(true);}
  function resize(){const b=canvas.getBoundingClientRect();if(!b.width||!b.height)return;const changed=policy.resize(b.width,b.height),aspect=b.width/b.height;if(!changed&&Math.abs(camera.aspect-aspect)<1e-6)return;camera.aspect=aspect;fit(true);controls.update();invalidate();}
  controls.addEventListener('change',invalidate);controls.addEventListener('start',()=>policy.beginInteraction());controls.addEventListener('end',()=>{policy.endInteraction();invalidate();});
  const ro=new ResizeObserver(resize);ro.observe(canvas);const io=new IntersectionObserver(([e])=>{inView=e.isIntersecting;if(inView)invalidate();});io.observe(canvas);
  document.addEventListener('visibilitychange',()=>{if(document.hidden){cancelAnimationFrame(raf);raf=0;}else{last=performance.now();invalidate();}},{signal:abort.signal});
  canvas.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.code))return;e.preventDefault();const s=new T.Spherical().setFromVector3(camera.position.clone().sub(controls.target));s.theta+=(e.code==='ArrowRight'?.12:0)-(e.code==='ArrowLeft'?.12:0);s.phi+=(e.code==='ArrowDown'?.12:0)-(e.code==='ArrowUp'?.12:0);s.makeSafe();camera.position.setFromSpherical(s).add(controls.target);controls.update();invalidate(true);},{signal:abort.signal});
  canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();lost=true;controls.enabled=false;cancelAnimationFrame(raf);raf=0;onError(new Error('WebGL context lost'));},{signal:abort.signal});
  canvas.addEventListener('webglcontextrestored',()=>{if(disposed)return;lost=false;controls.enabled=true;policy.invalidateShadow();onReady();invalidate(true);},{signal:abort.signal});
  setView('front');resize();policy.beforeRender(performance.now());renderer.render(scene,camera);ready=true;diagnostics(performance.now(),true);onReady();invalidate(true);
  return {ready:world.ready,setView,
    setTurn(value){turn=Boolean(value);last=performance.now();invalidate(true);},
    setSeparated(value){separated=Boolean(value);last=performance.now();invalidate(true);},
    setStudy(value){scene.overrideMaterial=value?clay:null;policy.invalidateShadow();invalidate(true);},
    setLight(value){light=value?'silver':'studio';key.color.set(value?'#e2eeff':'#fff7eb');scene.environmentIntensity=value?.61:.40;policy.invalidateShadow();invalidate(true);},
    setDetail(name){stop();detail=Object.hasOwn(world.root.userData.detailTargets,name)?name:'paper';world.root.rotation.set(0,0,0);controls.target.fromArray(world.root.userData.detailTargets[detail]);const offset={paper:[-.22,.20,2.2],cords:[.25,.13,2.25],strata:[-.15,.20,2.20]}[detail];camera.position.copy(controls.target).add(V3(offset));camera.fov=33;camera.updateProjectionMatrix();controls.update();invalidate(true);},
    reset(){separated=false;amount=0;world.setSeparated(0);scene.overrideMaterial=null;light='studio';key.color.set('#fff7eb');scene.environmentIntensity=.40;setView('front');},
    suspend(value){suspended=Boolean(value);if(suspended){cancelAnimationFrame(raf);raf=0;}else{last=performance.now();invalidate(true);}diagnostics(performance.now(),true);},
    stats(){diagnostics(performance.now(),true);return {...canvas.dataset,...world.root.userData,rootScale:world.root.scale.toArray()};},
    async capture({background=true}={}){if(lost||disposed)throw new Error('Renderer unavailable');policy.invalidateShadow();policy.beforeRender(performance.now());renderer.render(scene,camera);let target=canvas;if(background){target=document.createElement('canvas');target.width=canvas.width;target.height=canvas.height;const x=target.getContext('2d');x.fillStyle=PAPER;x.fillRect(0,0,target.width,target.height);x.drawImage(canvas,0,0);}return new Promise((resolve,reject)=>target.toBlob(b=>b?resolve(b):reject(new Error('Capture failed')),'image/png'));},
    async exportGLB(){const{GLTFExporter}=await import('three/addons/exporters/GLTFExporter.js');const rotation=world.root.rotation.clone();try{world.root.rotation.set(0,0,0);world.setSeparated(0);world.root.updateMatrixWorld(true);return await new GLTFExporter().parseAsync(world.root,{binary:true,onlyVisible:true,maxTextureSize:768});}finally{world.root.rotation.copy(rotation);world.setSeparated(amount);invalidate(true);}},
    dispose(){if(disposed)return;disposed=true;cancelAnimationFrame(raf);abort.abort();ro.disconnect();io.disconnect();policy.dispose();controls.dispose();world.dispose();clay.dispose();key.shadow.dispose();env.dispose();scene.clear();renderer.dispose();}
  };
}
const V3=values=>new T.Vector3(...values);
